### ISSUE TITLE
How to use this without expo?

### ISSUE THREAD

**Issue by creativemind1** [rahulhaque/compass-react-native-expo#1]
Hello,

I want to install this module but I don't have expo. My App is without expo and on pure react-native. Can I still able to run this?

Thanks

**Comment by rahulhaque** [comment]
Hello there. The modules I've imported from `expo` here are `Magnetometer` and `ScreenOrientation`. The rest of the app is using react native components and I think the logic will also be the same for `react-native-sensors`. You should search for equivalent `react-native` modules for `Magnetometer`. Import them and try them out. Here is a something related to this - [https://react-native-sensors.github.io/](https://react-native-sensors.github.io)

**Comment by creativemind1** [comment]
Thanks for your reply. Your this module is wonderful. I will see with the react-native modules Magnetometer and ScreenOrientation, whether it will support or not.

Thanks

**Comment by creativemind1** [comment]
I tried it using the react native sensors (with Accelerometer) along with your code. The rotation is not moving accordingly... I think we should need Magnetometer but there is no such thing in React Native. Can you advice?

**Comment by rahulhaque** [comment]
React native sensors has api for magnetometer but there is hardly any example available. Did you follow the installation instructions as is. The listeners for magnetometer in `expo` and in `react-native-sensors` are different. You should try out both. I suppose this is the furthest I can guide you in this. I may tinker with `react-native-sensors` when I get enough time. Thank you.

**Comment by rahulhaque** [comment]
@creativemind1 Hello there. I have tested my app logic with `react-native-sensors` and it is working perfectly fine. I am running the app on Android. The installation process was a bit tricky for `react-native-sensors`. You should go through all the steps described [here](https://react-native-sensors.github.io/docs/Installation.html). If that works for you, be sure to close the issue.
