### ISSUE TITLE
TypeError: "subscription" is read-only

### ISSUE THREAD

**Issue by mail4hafij** [rahulhaque/compass-react-native-expo#5]
You can't set a value on a react state variable 'subscription' like this. Must use setSubscription. Pretty basic mistake.
https://github.com/rahulhaque/compass-react-native-expo/blob/1f1b5b46c794a55a88b46fc81e213bfc2d66680b/App.js#L38

**Comment by rahulhaque** [comment]
Thanks for taking the time to review. From what I remember, this was done deliberately to reduce an extra render call as it was used with `useEffect` hooks.

**Comment by mail4hafij** [comment]
Whatever the case maybe - you can not set a react state variable 'subscription' with an 'equal' operator. You must use the 'setSubscription' method to set/modify the state variable 'subscription'. This is because - useState returns a readonly variable, and a method to modify a state variable.

`const [subscription, setSubscription] = useState(null);`

**Comment by rahulhaque** [comment]
I agree. Fixed and closed.
