### ISSUE TITLE
Compass fluctation

### ISSUE THREAD

**Issue by Soumil1396** [rahulhaque/compass-react-native-expo#6]
The compass fluctuates when it is set to rest position after a rotation is made. For eg : - Starting point is 0 and a rotation is made till 130 degrees. Once set to rest it keeps on fluctuating between 130 and 131 degrees continuously . Any solution for this ?

**Comment by rahulhaque** [comment]
@Soumil1396 the fluctuation seems varies dependent on device and its built in magnetometer. It didn't bother me as the reading was accurate. You can try looking for any way to stabilize it.
